version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/frontend/Dify-ChatBot-V2"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"
