[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --cov=apps --cov-report=term-missing
# 這裡設定 pytest 尋找測試檔案的模式
# DJANGO_SETTINGS_MODULE 指定 Django 的設定檔位置
# addopts 加入 --cov 指定要統計覆蓋率的資料夾 (apps)
