# Generated by Django 6.0 on 2026-01-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_id', models.CharField(max_length=100, verbose_name='聊天室 ID')),
                ('user_message', models.TextField(verbose_name='使用者訊息')),
                ('bot_response', models.TextField(verbose_name='機器人回覆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '聊天記錄',
                'verbose_name_plural': '聊天記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
