# Generated by Django 6.0 on 2026-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_chatmessage_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='dify_conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dify Conversation ID'),
        ),
    ]
